a = int(input("Enter a value: "))
b = int(input("Enter b value: "))
print("sum: ",a+b)
print("difference: ",a-b)
print("difference: ",a-b)
print("Multipication: ",a*b)
print("Division(float): ",a/b)
print("Floor Division: ",a//b)
print("Modulo Division: ",a%b)
print("exponent: ",a**b)